export const DEFAULT_DASHBOARD_START_DATE = "2024-07-25";
export const DEFAULT_DASHBOARD_END_DATE = "2024-07-31";
export const DEFAULT_DASHBOARD_QUERY = `eventTimeStart=${DEFAULT_DASHBOARD_START_DATE}&eventTimeEnd=${DEFAULT_DASHBOARD_END_DATE}`;
